DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS orders;

REVOKE ALL PRIVILEGES ON DATABASE wb_test_db FROM wb_user;
DROP USER IF EXISTS wb_user;
